version: "3"

services:
  apprunnner:
    container_name: apprunnner
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    #command: npm run dev
